name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Sync dependencies (incl. dev)
        run: uv sync --group dev

      - name: Check formatting (Black)
        run: uv run black --check .

      - name: Run tests
        run: uv run pytest -q
